// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uiclcvtpifwbvfojxxtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpY2xjdnRwaWZ3YnZmb2p4eHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyODc1NTQsImV4cCI6MjA1NTg2MzU1NH0.6jhRwgwt9ODBz03wMeUggukbWw1fQ_P93GcnUUP1Py8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);